@baseUrl = http://localhost:5031
@token  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1c2VyM0BlbWFpbC5jb20iLCJleHAiOjE3NDE4MTA4NTUsImlzcyI6Ik15QXV0aFNlcnZlciIsImF1ZCI6Ik15QVBJIn0.MRVsfB2DGWFM0vuCJvrwhbGksjzgjnMUsDnkIyiHAI8"

POST {{baseUrl}}/api/account/login
Content-Type: application/json
{
    "username": "user3",
    "password": "1234"
}
###

POST {{baseUrl}}/api/account/register
Content-Type: application/json
{
    "username": "user2",
    "email": "user3@email.com",
    "password": "1234"
}
###

POST {{baseUrl}}/api/account/refresh
Content-Type: application/json
{
   "AccessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1c2VyM0BlbWFpbC5jb20iLCJleHAiOjE3NDE4MTAxMjAsImlzcyI6Ik15QXV0aFNlcnZlciIsImF1ZCI6Ik15QVBJIn0.6kUl0I-wHZ6CCahbA5TLDzxcM3Caei6EgjqLHCcg6mI",
   "RefreshToken":"73282EF081004D51A5992DA42DFCAAFFC67EC04A16AB74101044691BFBF505FB"
}
###

GET {{baseUrl}}/api/collections/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1c2VyM0BlbWFpbC5jb20iLCJleHAiOjE3NDE4MTI3MDIsImlzcyI6Ik15QXV0aFNlcnZlciIsImF1ZCI6Ik15QVBJIn0.GludpC-hjPSW6jYrBHaMHX53g9KwGNXDe27cRuopsEk
Content-Type: application/json
{

}
###

GET {{baseUrl}}/api/collections/debug
Content-Type: application/json
{
   
}
###