@baseUrl = http://localhost:5031
@token  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1c2VyMUBlbWFpbC5jb20iLCJleHAiOjE3NDE3Mjc3MTMsImlzcyI6Ik15QXV0aFNlcnZlciIsImF1ZCI6Ik15QVBJIn0.T_G7faWZgRwp1ioMugl50g4gepXtr0q97-5OqKIsSd8"

GET {{baseUrl}}/api/account/login
Content-Type: application/json
{
    "username": "user3",
    "password": "1234"
}
###

POST {{baseUrl}}/api/account/register
Content-Type: application/json
{
    "username": "user3",
    "email": "user3@email.com",
    "password": "1234"
}
###

POST {{baseUrl}}/api/collections/test
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
###